apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: owls-insight-frontend-ingress
  namespace: owls-insight-dev
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:482566359918:certificate/13669ac8-4b64-4025-9c9c-63dd721be665
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/tags: Environment=development, Application=owls-insight-frontend
    alb.ingress.kubernetes.io/group.name: owls-insight
spec:
  ingressClassName: alb
  rules:
    - host: owlsinsight.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: owls-insight-frontend
                port:
                  number: 80
    - host: www.owlsinsight.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: owls-insight-frontend
                port:
                  number: 80
