apiVersion: v1
kind: Service
metadata:
  name: owls-insight-frontend
  namespace: owls-insight-dev
  labels:
    app: owls-insight-frontend
spec:
  selector:
    app: owls-insight-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
